import 'animate.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import Drawer from './drawer/page';
import './globals.css';
import styles from './page.module.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})

{
  return (
<html lang="en">
  <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"></link>
      <link rel="preconnect" href="https://fonts.gstatic.com"></link>
      <link href="https://fonts.googleapis.com/css2?family=Spectral:ital,wght@1,200&display=swap" rel="stylesheet"></link>
  </head>
    <body className={inter.className}>
      <div className={styles.navaya}>
      <Drawer/>
      </div>
      {children}</body>
    </html>
  )
}

